nameOverride: "config-service"
fullnameOverride: "config-service"

replicaCount: 1
annotations: {}

image:
  repository: config-service
  tag: v0.0.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "0.5"
    memory: 512Mi

service:
  type: ClusterIP

ports:
  grpc: 5150

nodeSelector: {}

tolerations: []

affinity: {}

etcd:
  username: root
  secretName: etcd
  endpoints:
    - "http://etcd.opencnc.svc.cluster.local:2379"
    
tls:
  enabled: true
  secretName: opencnc-shared-cert
  mountPath: /certs

