apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-service.fullname" . }}
  labels:
    app: {{ include "config-service.name" . }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "config-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "config-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "config-service.imagename" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.ports.grpc }}
              protocol: TCP
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ETCD_USERNAME
              value: {{ .Values.etcd.username | quote }}
            - name: ETCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.etcd.secretName }}
                  key: etcd-root-password
            - name: ETCD_ENDPOINTS
              value: {{ join "," .Values.etcd.endpoints | quote }}
          volumeMounts:
            - name: certs
              mountPath: {{ .Values.tls.mountPath }}
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.tls.secretName }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

