replicaCount: 1

image:
  repository: quay.io/coreos/etcd
  tag: v3.5.13
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 2379
  peerPort: 2380

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  mountPath: /etcd-data

resources: {}

# ETCD endpoint info for other services
etcd:
  username: root
  secretName: etcd
  endpoints:
    - "http://etcd.opencnc.svc.cluster.local:2379"

